Add support for kibana dashboard spaces
stashed/elasticsearch pull request #1465
Opened 2024-02-07 06:37 UTC by ishtiaqhimel

2024-02-07 06:51 UTC, hmsayem requested changes

2024-02-07 06:51 UTC, hmsayem commented on pkg/utils.go
> +}
```go
func (opt *esOptions) getDashboardFilePath(space string) string {
	return filepath.join(opt.interimDir, space + ".ndjson")
}
```

2024-02-07 08:16 UTC, hmsayem approved these changes

2024-02-08 11:10 UTC, raihankhan approved these changes
LGTM!

2024-02-08 11:10 UTC, merged